- name: Practice file module
  hosts: servers

  tasks:
    - name: Create a directory
      file:
        path: /home/ubuntu/demo-folder
        state: directory

    - name: Create a file
      file:
        path: /home/ubuntu/demo-folder/test.txt
        state: touch

    - name: Change file permissions
      file:
        path: /home/ubuntu/demo-folder/test.txt
        mode: '0644'
